### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

### Reading the data

In [2]:
parts = 3

df_chiller01_list = []
df_chiller03_list = []

df_chiller01_list = [pd.read_excel(f'data/CF-01 pt{p}-202109-202111.xls') for p in range(1, parts+1)]
df_chiller03_list = [pd.read_excel(f'data/CF-03 pt{p}-202109-202111.xls') for p in range(1, parts+1)]

### Concatenating parts for each dataframe

In [3]:
df_chiller01_raw = pd.concat(df_chiller01_list, ignore_index=True)
df_chiller03_raw = pd.concat(df_chiller03_list, ignore_index=True)

In [4]:
df_chiller01_raw.Monitoração.unique()

array(['Rendimento', 'Carga Térmica',
       'Potência Ativa Trifásica  - MM - CF-01', 'Temperatura Ambiente',
       'Umidade Ambiente', 'Temperatura de Descarga',
       'Temperatura de RAG Depois da BAGP', 'Diferencial de Temperatura',
       'Vazão de Descarga', 'Temperatura de AAC'], dtype=object)

In [5]:
df_chiller03_raw.Monitoração.unique()

array(['Rendimento', 'Carga Térmica',
       'Potência Ativa Trifásica  - MM - CF-03', 'Temperatura Ambiente',
       'Umidade Ambiente', 'Temperatura de Descarga',
       'Temperatura de RAG Depois da BAGP', 'Diferencial de Temperatura',
       'Vazão de Descarga', 'Temperatura de AAC'], dtype=object)

### Merging date and time columns into one timestamp column

In [6]:
df_chiller01_raw['Timestamp'] = df_chiller01_raw['Data']+' '+df_chiller01_raw['Hora']
df_chiller03_raw['Timestamp'] = df_chiller03_raw['Data']+' '+df_chiller01_raw['Hora']

### Keeping only the rows that quality is  "Ok"

In [7]:
df_chiller01_raw = df_chiller01_raw[df_chiller01_raw['Qualidade'] == 'Ok']
df_chiller03_raw = df_chiller03_raw[df_chiller03_raw['Qualidade'] == 'Ok']

### Spliting the Dataframe for each variable

In [8]:
df_chiller01_raw[df_chiller01_raw['Monitoração'] == 'Rendimento'].Monitoração.unique()

array(['Rendimento'], dtype=object)

In [9]:
chiller1_vars = df_chiller01_raw.Monitoração.unique()
chiller3_vars = df_chiller03_raw.Monitoração.unique()

df_chiller01_list = []
df_chiller03_list = []

df_chiller01_list = [df_chiller01_raw[df_chiller01_raw['Monitoração'] == var] for var in chiller1_vars]
df_chiller03_list = [df_chiller03_raw[df_chiller03_raw['Monitoração'] == var] for var in chiller3_vars]

### Keeping  the rows that Thermal Load (Carga Térmica) is greater than 0

In [10]:
df_chiller01_list[1] = df_chiller01_list[1][df_chiller01_list[1]['Valor'] > 0]
df_chiller03_list[1] = df_chiller03_list[1][df_chiller03_list[1]['Valor'] > 0]

In [11]:
df_chiller01_list[1]

,Equipamento,Monitoração,Data,Hora,Qualidade,Valor,Unidade,Descrição,Timestamp
7811,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,01/09/2021,09:45:00,Ok,555.4,TR,-,01/09/2021 09:45:00
7812,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,01/09/2021,10:00:00,Ok,243.7,TR,-,01/09/2021 10:00:00
7813,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,01/09/2021,10:15:00,Ok,612.3,TR,-,01/09/2021 10:15:00
7814,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,01/09/2021,10:30:00,Ok,648.3,TR,-,01/09/2021 10:30:00
7815,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,01/09/2021,10:45:00,Ok,644.5,TR,-,01/09/2021 10:45:00
...,...,...,...,...,...,...,...,...,...
15536,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,20/11/2021,21:00:00,Ok,272.8,TR,-,20/11/2021 21:00:00
15537,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,20/11/2021,21:15:00,Ok,260.0,TR,-,20/11/2021 21:15:00
15538,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,20/11/2021,21:30:00,Ok,260.4,TR,-,20/11/2021 21:30:00
15539,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,20/11/2021,21:45:00,Ok,247.0,TR,-,20/11/2021 21:45:00
15540,AC - CAG 1 - PISO G4 - CF 01 - 31,Carga Térmica,20/11/2021,22:00:00,Ok,210.3,TR,-,20/11/2021 22:00:00

In [12]:
df_chiller03_list[1]

,Equipamento,Monitoração,Data,Hora,Qualidade,Valor,Unidade,Descrição,Timestamp
7812,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,01/09/2021,09:45:00,Ok,5.2,TR,-,01/09/2021 10:00:00
7813,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,01/09/2021,10:00:00,Ok,3.0,TR,-,01/09/2021 10:15:00
7834,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,01/09/2021,15:15:00,Ok,0.9,TR,-,01/09/2021 15:30:00
7840,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,01/09/2021,16:45:00,Ok,3.1,TR,-,01/09/2021 17:00:00
7841,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,01/09/2021,17:00:00,Ok,5.2,TR,-,01/09/2021 17:15:00
...,...,...,...,...,...,...,...,...,...
15545,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,20/11/2021,23:00:00,Ok,1.5,TR,-,20/11/2021 23:15:00
15546,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,20/11/2021,23:15:00,Ok,1.1,TR,-,20/11/2021 00:15:00
15547,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,20/11/2021,23:30:00,Ok,1.5,TR,-,20/11/2021 00:30:00
15548,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,20/11/2021,23:45:00,Ok,1.2,TR,-,20/11/2021 00:45:00
15549,AC - CAG 1 - PISO G4 - CF 03 - 31,Carga Térmica,21/11/2021,00:00:00,Ok,0.8,TR,-,21/11/2021 01:00:00

### Reseting the dfs index

In [13]:
for i in range(0, len(df_chiller01_list)):
    df_chiller01_list[i].reset_index(inplace=True)
    df_chiller01_list[i].drop(['index'], axis='columns', inplace=True)
    
for i in range(0, len(df_chiller03_list)):
    df_chiller03_list[i].reset_index(inplace=True)
    df_chiller03_list[i].drop(['index'], axis='columns', inplace=True)

C:\Users\natmc\AppData\Roaming\Python\Python39\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [14]:
 df_chiller03_list[2]

,Equipamento,Monitoração,Data,Hora,Qualidade,Valor,Unidade,Descrição,Timestamp
0,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,01/09/2021,00:00:00,Ok,0.0,kW,-,01/09/2021 01:15:00
1,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,01/09/2021,00:15:00,Ok,0.0,kW,-,01/09/2021 01:30:00
2,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,01/09/2021,00:30:00,Ok,0.0,kW,-,01/09/2021 01:45:00
3,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,01/09/2021,00:45:00,Ok,0.0,kW,-,01/09/2021 02:00:00
4,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,01/09/2021,01:00:00,Ok,0.0,kW,-,01/09/2021 02:15:00
...,...,...,...,...,...,...,...,...,...
7769,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,20/11/2021,22:15:00,Ok,0.0,kW,-,20/11/2021 23:45:00
7770,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,20/11/2021,22:30:00,Ok,0.0,kW,-,20/11/2021 00:00:00
7771,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,20/11/2021,22:45:00,Ok,0.0,kW,-,20/11/2021 00:15:00
7772,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,20/11/2021,23:00:00,Ok,0.0,kW,-,20/11/2021 00:30:00
7773,AC - CAG 1 - PISO G4 - CF 03 - 31,Potência Ativa Trifásica - MM - CF-03,20/11/2021,23:15:00,Ok,0.0,kW,-,20/11/2021 00:45:00

### Renaming Monitoração column

In [15]:
var_dict = {
    'Rendimento': 'rendimento',
    'Carga Térmica': 'carga_termica_TR',
    'Potência Ativa Trifásica  - MM - CF-01' : 'potencia_kW',
    'Potência Ativa Trifásica  - MM - CF-03' : 'potencia_kW',
    'Temperatura Ambiente': 'temp_ambiente_C',
    'Umidade Ambiente': 'umid_rel_%',
    'Temperatura de Descarga': 'temp_saida_C',
    'Temperatura de RAG Depois da BAGP': 'temp_entrada_C',
    'Diferencial de Temperatura': 'ur_delta_temp_C',
    'Vazão de Descarga': 'vazao_saida_m3h',
    'Temperatura de AAC': 'temp_entrada_cond_C'
}

In [16]:
for i in range(0, len(df_chiller01_list)):
    df_chiller01_list[i].rename(columns={'Valor' : var_dict[df_chiller01_list[i].loc[1, 'Monitoração']]}, inplace=True)
    
for i in range(0, len(df_chiller03_list)):
    df_chiller03_list[i].rename(columns={'Valor' : var_dict[df_chiller03_list[i].loc[1, 'Monitoração']]}, inplace=True)

C:\Users\natmc\AppData\Roaming\Python\Python39\site-packages\pandas\core\frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

### Creating a final df for each chiller with all the variables

In [17]:
df_chiller01 = df_chiller01_list[0].loc[:, ['Timestamp','Equipamento']]
df_chiller03 = df_chiller03_list[0].loc[:, ['Timestamp','Equipamento']]

In [18]:
for i in range(0, len(df_chiller01_list)):
    df_chiller01 = pd.merge(df_chiller01, df_chiller01_list[i].iloc[:, [5, -1]], how='inner', on='Timestamp' )

In [19]:
df_chiller01

,Timestamp,Equipamento,rendimento,carga_termica_TR,potencia_kW,temp_ambiente_C,umid_rel_%,temp_saida_C,temp_entrada_C,ur_delta_temp_C,vazao_saida_m3h,temp_entrada_cond_C
0,01/09/2021 09:45:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.16,555.4,301.83,21.1,91.4,13.0,17.6,5.0,365.1,22.9
1,01/09/2021 10:00:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.41,243.7,350.43,21.6,89.7,10.9,16.3,4.9,136.5,28.9
2,01/09/2021 10:15:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.16,612.3,349.55,22.0,85.7,10.2,15.6,5.4,342.9,27.7
3,01/09/2021 10:30:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.15,648.3,350.14,22.5,82.7,9.7,15.3,5.1,350.1,26.0
4,01/09/2021 10:45:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.16,644.5,351.34,22.8,80.6,9.4,14.8,5.2,360.0,25.8
...,...,...,...,...,...,...,...,...,...,...,...,...
2353,20/11/2021 21:00:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.18,272.8,166.30,20.9,72.0,9.6,11.8,2.4,373.8,24.6
2354,20/11/2021 21:15:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.18,260.0,162.32,21.1,70.9,9.6,11.7,2.3,374.4,24.6
2355,20/11/2021 21:30:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.18,260.4,161.12,21.3,70.4,9.6,11.7,2.3,375.0,24.7
2356,20/11/2021 21:45:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.18,247.0,156.06,20.7,73.4,9.5,11.5,2.1,373.5,24.7
2357,20/11/2021 22:00:00,AC - CAG 1 - PISO G4 - CF 01 - 31,0.19,210.3,142.90,21.1,73.0,9.4,11.1,1.7,374.1,24.4

In [20]:
for i in range(0, len(df_chiller03_list)):
    df_chiller03 = pd.merge(df_chiller03, df_chiller03_list[i].iloc[:, [5, -1]], how='inner', on='Timestamp' )

In [21]:
df_chiller03

,Timestamp,Equipamento,rendimento,carga_termica_TR,potencia_kW,temp_ambiente_C,umid_rel_%,temp_saida_C,temp_entrada_C,ur_delta_temp_C,vazao_saida_m3h,temp_entrada_cond_C
0,01/09/2021 10:00:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.00,5.2,0.0,20.1,95.1,15.4,13.1,-2.1,14.1,22.2
1,01/09/2021 10:15:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.00,3.0,0.0,20.3,94.2,15.4,13.2,-2.0,14.1,22.2
2,01/09/2021 15:30:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.00,0.9,0.0,23.9,84.5,15.5,13.5,-1.7,7.5,25.6
3,01/09/2021 17:15:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.00,5.2,0.0,24.2,87.9,14.5,14.3,-0.2,239.7,26.1
4,01/09/2021 17:30:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.00,3.2,0.0,24.0,89.4,14.5,14.2,-0.3,4.5,26.8
...,...,...,...,...,...,...,...,...,...,...,...,...
4450,20/11/2021 22:00:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.14,573.5,311.0,21.4,69.7,6.8,12.1,4.9,348.6,24.7
4451,20/11/2021 22:15:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.15,533.4,306.0,20.9,72.0,6.8,11.9,4.7,369.6,24.7
4452,20/11/2021 22:45:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.00,0.4,298.0,21.3,70.4,6.8,11.7,4.5,384.0,24.7
4453,20/11/2021 23:00:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.00,1.1,289.0,20.7,73.4,6.8,11.7,4.5,364.2,24.7
4454,20/11/2021 23:15:00,AC - CAG 1 - PISO G4 - CF 03 - 31,0.00,1.5,267.0,21.1,73.0,6.8,11.5,4.3,365.7,24.7

### Creating "carregamento" column

In [22]:
df_chiller01['carregamento_%'] = df_chiller01['carga_termica_TR']*100/650
df_chiller03['carregamento_%'] = df_chiller03['carga_termica_TR']*100/650

### Cleaning nonsense data

In [23]:
df_chiller01 = df_chiller01[(df_chiller01['carregamento_%'] < 100) & (df_chiller01['carregamento_%'] >= 1)]
df_chiller01 = df_chiller01[(df_chiller01['rendimento'] < 0.5) & (df_chiller01['rendimento'] > 0.1)]
df_chiller01 = df_chiller01[(df_chiller01['carga_termica_TR'] > 50)]

In [24]:
df_chiller03 = df_chiller03[(df_chiller03['carregamento_%'] < 100) & (df_chiller03['carregamento_%'] >= 1)]
df_chiller03 = df_chiller03[(df_chiller03['rendimento'] < 0.5) & (df_chiller03['rendimento'] > 0.1)]
df_chiller03 = df_chiller03[(df_chiller03['carga_termica_TR'] > 50)]
df_chiller03 = df_chiller03[(df_chiller03['potencia_kW'] > 0)]
df_chiller03 = df_chiller03[(df_chiller03['vazao_saida_m3h'] > 50) & (df_chiller03['vazao_saida_m3h'] < 600)]

### Checking the datasets

In [25]:
df_chiller01.describe()

,rendimento,carga_termica_TR,potencia_kW,temp_ambiente_C,umid_rel_%,temp_saida_C,temp_entrada_C,ur_delta_temp_C,vazao_saida_m3h,temp_entrada_cond_C,carregamento_%
count,1928.000000,1928.000000,1928.000000,1928.000000,1928.000000,1928.000000,1928.000000,1928.00000,1928.000000,1928.000000,1928.000000
mean,0.166312,433.149793,246.712873,25.295591,63.066494,8.997666,12.621214,3.54388,367.561618,26.193880,66.638430
std,0.033005,123.026897,64.157463,3.113615,14.401105,1.282354,1.159094,1.13800,33.391427,1.737248,18.927215
min,0.120000,79.200000,103.660000,18.200000,23.400000,6.600000,8.000000,0.30000,60.000000,20.400000,12.184615
25%,0.150000,331.225000,191.742500,23.300000,53.900000,7.900000,11.900000,2.70000,357.300000,24.900000,50.957692
50%,0.160000,420.700000,233.915000,25.100000,66.500000,9.300000,12.300000,3.30000,381.300000,26.100000,64.723077
75%,0.170000,538.050000,298.532500,27.600000,73.500000,9.600000,13.000000,4.50000,383.400000,27.200000,82.776923
max,0.470000,649.300000,360.700000,33.400000,95.600000,19.700000,20.700000,7.60000,466.500000,33.000000,99.892308

In [26]:
df_chiller03.describe()

,rendimento,carga_termica_TR,potencia_kW,temp_ambiente_C,umid_rel_%,temp_saida_C,temp_entrada_C,ur_delta_temp_C,vazao_saida_m3h,temp_entrada_cond_C,carregamento_%
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,0.151188,540.800938,291.619762,24.848780,63.488993,7.647467,12.694747,4.914259,333.841276,25.980363,83.200144
std,0.023087,87.728837,58.559196,3.390786,14.304977,1.055976,1.021715,1.066745,27.340683,2.509190,13.496744
min,0.110000,91.200000,1.000000,17.200000,23.800000,6.300000,8.000000,-0.700000,51.600000,18.400000,14.030769
25%,0.140000,499.650000,260.000000,22.200000,54.050000,7.000000,12.000000,4.500000,326.700000,24.500000,76.869231
50%,0.150000,557.600000,293.000000,24.700000,67.400000,7.400000,12.400000,5.100000,336.300000,25.900000,85.784615
75%,0.150000,606.300000,342.000000,27.350000,74.250000,7.700000,13.200000,5.600000,343.800000,27.400000,93.276923
max,0.420000,649.800000,364.000000,33.400000,86.100000,16.400000,17.100000,6.700000,472.500000,39.600000,99.969231

### Exporting csv data

In [27]:
df_chiller01.to_csv('data/chiller01.csv', sep=';')
df_chiller03.to_csv('data/chiller03.csv', sep=';')

## Creating dataset to get the average conditions
- Temperatura ambiente
- Umidade ambiente
- Temperatura de AAC

In [28]:
external_conditions = ['Temperatura Ambiente', 'Umidade Ambiente', 'Temperatura de AAC']

df_conditions_list = [df_chiller01_raw[df_chiller01_raw['Monitoração'] == var] for var in external_conditions]

#reseting indexes
for i in range(0, len(df_conditions_list)):
    df_conditions_list[i].reset_index(inplace=True)
    df_conditions_list[i].drop(['index'], axis='columns', inplace=True)
    
#renaming
for i in range(0, len(df_conditions_list)):
    df_conditions_list[i].rename(columns={'Valor' : var_dict[df_conditions_list[i].loc[1, 'Monitoração']]}, inplace=True)

#merging into onde df
df_conditions = df_conditions_list[0].loc[:, ['Timestamp']]

for i in range(0, len(df_conditions_list)):
    df_conditions = pd.merge(df_conditions, df_conditions_list[i].iloc[:, [5, -1]], how='outer', on='Timestamp' )
    
df_conditions = pd.DataFrame(df_conditions.mean()).T
df_conditions

C:\Users\natmc\AppData\Roaming\Python\Python39\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
C:\Users\natmc\AppData\Roaming\Python\Python39\site-packages\pandas\core\frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
<ipython-input-28-1dba28a2d472>:20: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_conditions = pd.DataFrame(df_conditions.mean()).T

   temp_ambiente_C  umid_rel_%  temp_entrada_cond_C
0        23.453017   68.987119            24.522896

### Mean operational conditions for each chiller

In [29]:
df_chiller01_mean = pd.DataFrame(df_chiller01.loc[:, ['temp_ambiente_C', 'umid_rel_%', 'temp_entrada_cond_C', 'temp_saida_C', 'temp_entrada_C', 'ur_delta_temp_C', 'vazao_saida_m3h']].mean()).T
#df_chiller01_mean = pd.concat([df_conditions, df_chiller01_mean], axis=1)
df_chiller01_mean

,temp_ambiente_C,umid_rel_%,temp_entrada_cond_C,temp_saida_C,temp_entrada_C,ur_delta_temp_C,vazao_saida_m3h
0,25.295591,63.066494,26.19388,8.997666,12.621214,3.54388,367.561618

In [30]:
df_chiller03_mean = pd.DataFrame(df_chiller03.loc[:, ['temp_ambiente_C', 'umid_rel_%', 'temp_entrada_cond_C', 'temp_saida_C', 'temp_entrada_C', 'ur_delta_temp_C', 'vazao_saida_m3h']].mean()).T
#df_chiller03_mean = pd.concat([df_conditions, df_chiller03_mean], axis=1)
df_chiller03_mean

,temp_ambiente_C,umid_rel_%,temp_entrada_cond_C,temp_saida_C,temp_entrada_C,ur_delta_temp_C,vazao_saida_m3h
0,24.84878,63.488993,25.980363,7.647467,12.694747,4.914259,333.841276

In [31]:
df_chiller01_mean.to_csv('data/chiller01_mean.csv', sep=';')
df_chiller03_mean.to_csv('data/chiller03_mean.csv', sep=';')